config/routes.rb
Rails.application.routes.draw do
  root 'games#new'
  resources :games do
    resources :hands
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
	validates :player1, :amount, presence: true
	has_many :hands

	def self.sort_by_recent
		order("id DESC")
	end

	def query_hands
		Hand.where(game_id: self.id).order("id ASC")
	end

	def total_score(player)
    if player == 1
    	query_hands.sum(:score1)
    elsif player == 2
    	query_hands.sum(:score2)
    elsif player == 3
    	query_hands.sum(:score3)
    elsif player == 4
    	query_hands.sum(:score4)
    end
	end

	def total_score_all_players
		score_array = []
		for i in 1..4
			score_array.push(total_score(i))
		end
		score_array
	end

	def check_no_player_name
		if player1 == ""
			self.player1 = "Player 1"
		end

		if player2 == ""
			self.player2 = "Player 2"
		end

		if player3 == ""
			self.player3 = "Player 3"
		end

		if player4 == ""
			self.player4 = "Player 4"
		end
	end

	def calculate_owe
		score_array = total_score_all_players
		final_owe = []
		for i in 0..score_array.length-1
			current_player_owe = []
			current_player_score = score_array[i]
      for j in 0..score_array.length-1
        if j == i
          current_player_owe.push(0)
        else
        	if current_player_score > score_array[j]
            converted_score = (current_player_score - score_array[j]) * self.amount
        		current_player_owe.push(converted_score)
        	else
        	  current_player_owe.push(0) 
        	end
        end 
      end
      final_owe.push(current_player_owe)
		end
		final_owe
	end
end

app/models/hand.rb
class Hand < ActiveRecord::Base
	validates :score1, :score2, :score3, :score4, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 65}
	belongs_to :game

	def update_score
		self.score1 = score_multiplier(self.score1)
		self.score2 = score_multiplier(self.score2)
		self.score3 = score_multiplier(self.score3)
		self.score4 = score_multiplier(self.score4)
	end

	def score_multiplier(score)
		if score == nil
			0
		elsif score == 13
			score * 5
		elsif score >= 11
			score * 4
		elsif score >= 8
			score * 3
		elsif score >= 5
			score * 2
		else
			score
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :set_game, only: [:show]

	def index
		@games = Game.all.sort_by_recent
	end

	def show
		@hands = @game.query_hands
		@hand = Hand.new
		@owe_array = @game.calculate_owe
	end

	def new
		@game = Game.new
	end

	def create
		@game = Game.new(game_params)
		@game.check_no_player_name
		if @game.save
			redirect_to @game, notice: "Game was successfully created"
		else
			render :new, alert: "Check yo fields"
		end
	end

	private
  def set_game
  	@game = Game.find(params[:id])
  end

  def game_params
  	params.require(:game).permit(:nickname, :player1, :player2, :player3, :player4, :amount)
  end
end

app/controllers/hands_controller.rb
class HandsController < ApplicationController
	before_action :set_hand, only: [:show, :edit, :update, :destroy]
  before_action :set_game, only: [:create, :update, :edit, :destroy]

	def show
	end

	def new
		@hand = Hand.new
	end

	def create
		@hand = Hand.new(hand_params)
		@hand.game_id = @game.id
		@hand.update_score
		if @hand.save
			redirect_to @game, notice: "Hand was successfully added"
		else
			redirect_to @game, alert: "Failed to update. Make sure the hand score is between 0-13"
		end
	end

	def edit
	end

	def update
    if @hand.update(hand_params)
    	redirect_to game_path(@game), notice: "Hand successfully changed"
    else
    	redirect_to edit_game_hand_path(@game, @hand), alert: "Incorrect field submission"
    end
	end

	def destroy
		if @hand.destroy
			redirect_to @game, notice: "Hand was successfully deleted"
		else
			redirect_to edit_game_hand_path(@game, @hand), alert: "Hand failed to delete"
		end
	end

	private

	def set_game
		@game = Game.find(params[:game_id])
	end

	def set_hand
		@hand = Hand.find(params[:id])
	end

	def hand_params
		params.require(:hand).permit(:score1, :score2, :score3, :score4, :game_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/hands_helper.rb
module HandsHelper
end

app/views/games/_form.html.erb
<%= form_for @game do |f| %>

  <div class="input-group col-xs-10 col-sm-7 input-player">
  	<span class="input-group-addon"><i class="fa fa-heart"></i></span>
	  <%= f.text_field :nickname, placeholder: "Nickname for Game (Optional)", class: "form-control no-border-radius" %>
  </div>

  <div class="input-group col-xs-10 col-sm-7 input-player">
  	<span class="input-group-addon"><i class="fa fa-dollar"></i></span>
	  <%= f.number_field :amount, placeholder: "Amount per card", step: "0.01", class: "form-control no-border-radius" %>
  </div>
	
  <div class="input-group col-xs-10 col-sm-7 input-player">
  	<span class="input-group-addon"><i class="fa fa-user"></i></span>
	  <%= f.text_field :player1, placeholder: "Player 1", class: "form-control no-border-radius"  %>
  </div>

  <div class="input-group col-xs-10 col-sm-7 input-player">
  	<span class="input-group-addon"><i class="fa fa-user"></i></span>
	  <%= f.text_field :player2, placeholder: "Player 2", class: "form-control no-border-radius"  %>
  </div>

  <div class="input-group col-xs-10 col-sm-7 input-player">
  	<span class="input-group-addon"><i class="fa fa-user"></i></span>
	  <%= f.text_field :player3, placeholder: "Player 3", class: "form-control no-border-radius"  %>
  </div>

  <div class="input-group col-xs-10 col-sm-7 input-player">
  	<span class="input-group-addon"><i class="fa fa-user"></i></span>
	  <%= f.text_field :player4, placeholder: "Player 4", class: "form-control no-border-radius"  %>
  </div>
  
  <div class="input-group col-xs-10 col-sm-7 col-xs-offset-4 col-sm-offset-5">
	  <span class="input-group-btn">
	    <%= f.submit "Create Game", class: "btn btn-lg btn-success create-game-button" %>
	  </span>
  </div>

<% end %>

app/views/games/index.html.erb
<h1 class="game-title ">List of Games</h1>
<h3 class="page-description">(Most recent first)</h3>
<% @games.each do |game| %>
  <div class="game-link-container">
  <% if game.nickname != "" %>
    <%= link_to game.nickname, game %>
  <% else %>
    <%= link_to "Game " + game.id.to_s, game %>
  <% end %>
  </div>
<% end %>

app/views/games/new.html.erb
<h1 class="game-title">Create a new game</h1>
<%= render 'form' %>

app/views/games/show.html.erb
<h1 class="game-title "><%= @game.nickname ? "#{@game.nickname}" : "Game #{@game.id}"%></h1>

<%= form_for [@game, @hand] do |f| %>
	  <div class="input-group col-xs-10 col-sm-7 input-player">
  	<span class="input-group-addon"><i class="fa fa-dollar"></i></span>
	  <%= f.number_field :score1, placeholder: "#{@game.player1} Score", min: 0, max: 13, step: 1, class: "form-control no-border-radius"  %>
  </div>

  <div class="input-group col-xs-10 col-sm-7 input-player">
  	<span class="input-group-addon"><i class="fa fa-dollar"></i></span>
	  <%= f.number_field :score2, placeholder: "#{@game.player2} Score", min: 0, max: 13, step: 1, class: "form-control no-border-radius"  %>
  </div>


  <div class="input-group col-xs-10 col-sm-7 input-player">
  	<span class="input-group-addon"><i class="fa fa-dollar"></i></span>
	  <%= f.number_field :score3, placeholder: "#{@game.player3} Score", min: 0, max: 13, step: 1, class: "form-control no-border-radius"  %>
  </div>

  <div class="input-group col-xs-10 col-sm-7 input-player">
  	<span class="input-group-addon"><i class="fa fa-dollar"></i></span>
	  <%= f.number_field :score4, placeholder: "#{@game.player4} Score", min: 0, max: 13, step: 1, class: "form-control no-border-radius"  %>
  </div>
  
  <div class="input-group col-xs-10 col-sm-7 col-xs-offset-4 col-sm-offset-5">
	  <span class="input-group-btn">
	    <%= f.submit "Submit Hand", class: "btn btn-lg btn-success create-hand-button" %>
	  </span>
  </div>
<% end %>

<p>Click on hand # to edit it</p>
<div class="table-responsive">
  <table class="table table-bordered table-striped">
    <thead>
    	<tr>
    		<th>Hand #</th>
    		<th><%= @game.player1 %></th>
    		<th><%= @game.player2 %></th>
    		<th><%= @game.player3 %></th>
    		<th><%= @game.player4 %></th>
    	</tr>
    </thead>
    <tbody>
      <% hand_count = 1 %>
    	<% @hands.each do |hand| %>
        
    	  <tr>
          <td><%= link_to "#{hand_count}", edit_game_hand_path(@game, hand) %></td>
          <td><%= "#{hand.score1}"%></td>
          <td><%= "#{hand.score2}"%></td>
          <td><%= "#{hand.score3}"%></td>
          <td><%= "#{hand.score4}"%></td>
    	  </tr>
        <% hand_count += 1 %>
    	<% end %>
    </tbody>
  </table>
</div>

<div class="table-responsive total-table">
  <table class="table table-bordered">
  	<caption class="total-title">Total Score</caption>
    <thead>
    	<tr>
    		<th><%= @game.player1 %></th>
    		<th><%= @game.player2 %></th>
    		<th><%= @game.player3 %></th>
    		<th><%= @game.player4 %></th>
    	</tr>
    </thead>
    <tbody>
    	<tr>
    		<th><%= @game.total_score(1) %></th>
    		<th><%= @game.total_score(2) %></th>
    		<th><%= @game.total_score(3) %></th>
    		<th><%= @game.total_score(4) %></th>
    	</tr>
    </tbody>
  </table>
</div>


<div class="table-responsive total-table total-owe">
  <p>First column is person owing. Person owes the amount to others on the same row horizontally.</p>
  <table class="table table-bordered table-striped">
    <caption class="total-title">Total Owing</caption>
    <thead>
      <tr>
        <th><%= "Player \\ Player Owed" %>
        <th><%= @game.player1 %></th>
        <th><%= @game.player2 %></th>
        <th><%= @game.player3 %></th>
        <th><%= @game.player4 %></th>
      </tr>
    </thead>
    <tbody>
      <% player_names = [@game.player1, @game.player2, @game.player3, @game.player4] %>
      <% for i in 0..((@owe_array.length)-1) %>
        <tr>
          <th><%= player_names[i] %></th>
        <% for j in 0..((@owe_array.length)-1) %> 
          <th>$<%= @owe_array[i][j] %></th>
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="input-group col-xs-10 col-sm-7 col-xs-offset-4 col-sm-offset-5">
  <%= button_tag "Toggle Total", class: "btn btn-lg btn-primary total-button" %>
</div>

app/views/hands/_form.html.erb
<%= form_for [@game, @hand] do |f| %>
	  <div class="input-group col-xs-10 col-sm-7 input-player">
	  	<%= f.label "#{@game.player1}" %>
		  <%= f.number_field :score1, placeholder: "Player 1 Score", min: 0, max: 13, step: 1, class: "form-control no-border-radius"  %>
	  </div>

  <div class="input-group col-xs-10 col-sm-7 input-player">
  	<%= f.label "#{@game.player2}" %>
	  <%= f.number_field :score2, placeholder: "Player 2 Score", min: 0, max: 13, step: 1, class: "form-control no-border-radius"  %>
  </div>


  <div class="input-group col-xs-10 col-sm-7 input-player">
  	<%= f.label "#{@game.player3}" %>
	  <%= f.number_field :score3, placeholder: "Player 3 Score", min: 0, max: 13, step: 1, class: "form-control no-border-radius"  %>
  </div>

  <div class="input-group col-xs-10 col-sm-7 input-player">
  	<%= f.label "#{@game.player4}" %>
	  <%= f.number_field :score4, placeholder: "Player 4 Score", min: 0, max: 13, step: 1, class: "form-control no-border-radius"  %>
  </div>
  
  <div class="input-group col-xs-10 col-sm-7 col-xs-offset-4 col-sm-offset-5">
	  <span class="input-group-btn">
	    <%= f.submit "Submit Hand", class: "btn btn-lg btn-success create-hand-button" %>
	  </span>
  </div>
<% end %>

app/views/hands/edit.html.erb
<h1 class="game-title">Edit Hand Score</h1>
<div class="input-group col-xs-10 col-sm-7 col-xs-offset-4 col-sm-offset-5">
	<%= button_to "Delete Hand", game_hand_path(@game, @hand), method: :delete, class: "btn btn-danger btn-small", confirm: "Do you want to delete this hand?" %>
</div>
<%= render 'form' %>
<div class="input-group col-xs-10 col-sm-7 col-xs-offset-4 col-sm-offset-5">
  <%= button_to "Cancel", @game, method: :get, class: "btn btn-warning btn-lg" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Big2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Big 2", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "New Game", new_game_path %></li>
            <li><%= link_to "List of Games", games_path %></li>
            <!-- <li><a href="#contact">Contact</a></li> -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span></button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span></button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

</body>
</html>